controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


#Root spécifique
bonjour:
    path: /bonjour
    controller: App\Controller\HomeController::bonjour

accueil : 
    path: /
    controller: App\Controller\HomeController::accueil